targets:
  $default:
    builders:
      slang_build_runner:
        options:
          input_directory: lib/i18n
          input_file_pattern: .json
          output_directory: lib/gen
          flat_map: false
