name: ikus_app
description: IKUS OvGU App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.1+50

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # core
  intl: ^0.16.1 # used by table_calendar and for formatting dates
  fast_i18n: ^2.1.0 # translations
  jaguar_jwt: ^2.1.6 # jwt
  package_info: ^0.4.3 # show version and build of the app
  uuid: ^2.2.2 # create device id
  html: ^0.14.0+4 # parse html

  # storage
  hive: ^1.4.4 # persistent storage
  hive_flutter: ^0.3.1 # helper for hive
  flutter_secure_storage: ^3.3.5 # for ovgu account

  # native utilities
  http: ^0.12.2 # make http requests
  add_2_calendar: ^1.4.0 # add calendar reminders
  map_launcher: ^1.0.0 # launch external map app
  url_launcher: ^5.7.10 # open links
  enough_mail: # emails (wait for next release)
    git:
      url: git@github.com:Enough-Software/enough_mail.git
      ref: 26a10fab50e938a787714194ee0d970810768b0a
  workmanager: # run tasks in background (use PR version for now)
    git:
      url: git@github.com:ened/flutter_workmanager.git
      ref: 1c4e162ea4e71855856fb9e55a1545b3dae9a25d
  flutter_local_notifications: ^3.0.1+5 # show notifications

  # components
  flutter_html: ^1.0.2 # show post content encoded in html
  flutter_map: ^0.10.1 # show event location in-app
  carousel_slider: ^2.3.1 # slider (e.g. home page)
  table_calendar: ^2.3.1 # calendar
  native_pdf_view: ^3.8.0 # render handbook as pdf

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  hive_generator: ^0.8.2
  build_runner: any
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/img/maps/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
